### ISSUE TITLE
Failed to resolve expression: ${version}

### ISSUE THREAD

**Issue by AlecKotovichSAM** [helpermethod/p2e#14]
```
 jbang p2e@helpermethod spring.application.name

[jbang] [ERROR] Failed to resolve expression: ${version}

[jbang] Run with --verbose for more details
```

```
> jbang --verbose p2e@helpermethod spring.application.name
[jbang] [0:256] jbang version 0.116.0
[jbang] [0:272] Resolving resource ref: p2e@helpermethod
[jbang] [0:282] Reading catalog from C:\Users\***\.jbang\implicit-catalog.json
[jbang] [0:337] Using cached file C:\Users\***\.jbang\cache\urls\a5dc98ec173ceaad96972807f3f405015ecb0c76c9603e37e93c9d124a6166fc\jbang-catalog.json for remote https://raw.githubusercontent.com/helpermethod/jbang-catalog/HEAD/jbang-catalog.json
[jbang] [0:337] Reading catalog from https://github.com/helpermethod/jbang-catalog/blob/HEAD/jbang-catalog.json
[jbang] [0:338] Obtained catalog from https://github.com/helpermethod/jbang-catalog/blob/HEAD/jbang-catalog.json
[jbang] [0:341] Reading catalog from classpath:/jbang-catalog.json
[jbang] [0:345] Using cached file C:\Users\***\.jbang\cache\urls\9e5f036f349563e036ce916208ce6a69cea71bd388666b1793f22c8ed96ad73a\jbang-catalog.json for remote https://raw.githubusercontent.com/jbanghub/jbang-catalog/main/jbang-catalog.json
[jbang] [0:345] Reading catalog from https://raw.githubusercontent.com/jbanghub/jbang-catalog/main/jbang-catalog.json
[jbang] [0:347] Obtained catalog from https://raw.githubusercontent.com/jbanghub/jbang-catalog/main/jbang-catalog.json
[jbang] [0:349] Using cached file C:\Users\***\.jbang\cache\urls\f1eeb6bc8feb0042e3ade0f02a5334844301f1c496136741793b6b72191ac3eb\p2e.java for remote https://raw.githubusercontent.com/helpermethod/p2e/main/p2e.java
[jbang] [0:349] Resolved resource ref as: https://github.com/helpermethod/p2e/blob/main/p2e.java (cached as: C:\Users\***\.jbang\cache\urls\f1eeb6bc8feb0042e3ade0f02a5334844301f1c496136741793b6b72191ac3eb\p2e.java)
[jbang] [0:362] [ERROR] Failed to resolve expression: ${version}
java.lang.IllegalStateException: Failed to resolve expression: ${version}
        at dev.jbang.util.PropertiesValueResolver.replaceProperties(PropertiesValueResolver.java:119)
        at dev.jbang.source.ProjectBuilder.lambda$createSource$5(ProjectBuilder.java:347)
        at dev.jbang.source.TagReader.toKeyValue(TagReader.java:132)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at dev.jbang.source.TagReader.collectManifestOptions(TagReader.java:109)
        at dev.jbang.source.ProjectBuilder.updateProject(ProjectBuilder.java:503)
        at dev.jbang.source.ProjectBuilder.updateProjectMain(ProjectBuilder.java:476)
        at dev.jbang.source.ProjectBuilder.createSourceProject(ProjectBuilder.java:342)
        at dev.jbang.source.ProjectBuilder.build(ProjectBuilder.java:270)
        at dev.jbang.source.ProjectBuilder.build(ProjectBuilder.java:219)
        at dev.jbang.cli.Run.doCall(Run.java:73)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at dev.jbang.cli.JBang$3.handle(JBang.java:148)
        at dev.jbang.cli.JBang$3.handle(JBang.java:143)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.jbang.Main.main(Main.java:14)
[jbang] [0:381] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
```

**Comment by helpermethod** [comment]
Hi @AlecKotovichSAM,

thanks for reporting. I normally use the Homebrew version, so didn't realize the script doesn't work. Expect a fix ASAP.

**Comment by helpermethod** [comment]
Hi @AlecKotovichSAM ,

`p2e` should now also work properly with `jbang`.

**Comment by AlecKotovichSAM** [comment]
yes, now it is working, thanks!
